### ISSUE TITLE
"RNCustomTwilioVideoView" does not exist

### ISSUE THREAD

**Issue by kapilkarda** [blackuy/react-native-twilio-video-webrtc#81]
### Steps to reproduce
1.Create a fresh react app
2.Install the plugin as per the readme file and link it via react-native link
3.Just run the application it gives an error

### Expected behaviour
It should run the application on device, I have generated token and set the room name on a dummy app.

### Actual behaviour
It gives an error snapshot attached

### Environment
- **Node.js version**: V8.9.3
- **React Native version**:0.51.0
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: npm version or "master" 1.0.1

Demo Source Code : https://github.com/kapilkarda/twilio-video-demo

![image](https://user-images.githubusercontent.com/4336836/34861339-2f6ad494-f78a-11e7-8686-21dea66e244a.png)

**Comment by carlmagumpara** [comment]
check your android folder permission

**Comment by slycoder** [comment]
Just circling back, is this still happening on master?

**Comment by kamlesh-cis** [comment]
@slycoder yeah I am also having the same issue with the plugin 
https://github.com/blackuy/react-native-twilio-video-webrtc/

Can you suggest what will be the best fix for it 

Thanks

**Comment by slycoder** [comment]
@kamlesh-cis Do you have a repo or example of it failing?  Is this happening on iOS or Android for you?  Are you running master?

**Comment by harrydema** [comment]
I fixed on the example on this PR: #147

**Comment by slycoder** [comment]
Thanks @harrydema!

**Comment by akshay-squareboat** [comment]
It's still occurring and I am getting the same Error. Is there any fix for this ?

**Comment by slycoder** [comment]
Ok, I realized that the example hadn't been updated.  Can you try pulling down the changes in #282 and see if that fixes things?
